name: app_environment
channels:
  - snowflake
dependencies:
  - python=3.8.*
  - snowflake-snowpark-python=
  - streamlit=
  - snowflake-sqlalchemy
  - snowflake-snowpark-python=1.9.0
  - snowflake-connector-python=3.11.0
