name: app_environment
pip install snowflake-connector-python==3.11.0
pip install snowflake-snowpark-python==1.9.0
channels:
  - snowflake
dependencies:
  - python=3.9.*
  - snowflake-snowpark-python=
  - streamlit=
  - snowflake-sqlalchemy
  - snowflake-snowpark-python=1.9.0
  - snowflake-connector-python=3.9.0
